#!/usr/bin/env ansible-playbook

- name: show return value of a command module
  hosts: webservers
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}"
#    - debug: msg="Logged in as user {{ login['stdout'] }}"

    # - name: run myprog
    #   command: /opt/myprog
    #   register: result
    #   ignore_errors: True
    # - debug: var=result

- name: print out operating system
  hosts: vagrants
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution
